spring:
  application:
    name: "my-spring-boot-admin-n-config-client-app"

  cloud:
    config:
      uri:

  boot:
    admin:
      client:
        url:

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  environment:
    decorator:
      prefix: